config:
  PROVIDER_URI: https://prod-base-mainnet-us-east-1.blockchain.circle.com:8545
  STREAM_OUTPUT: projects/circle-ds-pipelines/topics/base
  ROOT_ENTITY_TYPE: block
  ENTITY_TYPES: block,transaction,log,token_transfer
  GCS_PREFIX: gs://circle-blockchain-etl-streaming/base
  CHAIN: base
  CHAIN_TYPE: ethereum
  LAG_BLOCKS: 30
  BLOCK_BATCH_SIZE: 10

stream:
  resources:
    requests:
      memory: "2048Mi"
      cpu: "300m"
    limits:
      memory: "4096Mi"
      cpu: "800m"