config:
  PROVIDER_URI: https://bsc-dataseed4.binance.org/
  STREAM_OUTPUT: projects/circle-ds-pipelines/topics/bnb
  ROOT_ENTITY_TYPE: block
  ENTITY_TYPES: block,transaction,log,token_transfer
  GCS_PREFIX: gs://circle-blockchain-etl-streaming/bnb
  CHAIN: bnb
  CHAIN_TYPE: ethereum
  LAG_BLOCKS: 300
  BLOCK_BATCH_SIZE: 5

stream:
  resources:
    requests:
      memory: "2048Mi"
      cpu: "300m"
    limits:
      memory: "4096Mi"
      cpu: "800m"