config:
  PROVIDER_URI: https://prod-ethereum-mainnet-us-east-1.blockchain.circle.com:8545/
  STREAM_OUTPUT: projects/circle-ds-pipelines/topics/ethereum
  ROOT_ENTITY_TYPE: block
  ENTITY_TYPES: block,transaction,log,token_transfer
  GCS_PREFIX: gs://circle-blockchain-etl-streaming/ethereum
  CHAIN: base
  CHAIN_TYPE: ethereum
  LAG_BLOCKS: 15
  BLOCK_BATCH_SIZE: 10
