config:
  PROVIDER_URI: https://rpc.ftm.tools/
  STREAM_OUTPUT: projects/circle-ds-pipelines/topics/fantom
  ROOT_ENTITY_TYPE: block
  ENTITY_TYPES: block,transaction,log,token_transfer
  GCS_PREFIX: gs://circle-blockchain-etl-streaming/fantom
  CHAIN: fantom
  CHAIN_TYPE: ethereum
  LAG_BLOCKS: 30
  BLOCK_BATCH_SIZE: 250