config:
  PROVIDER_URI: https://rpc.mantle.xyz,https://mantle-mainnet.public.blastapi.io	
  STREAM_OUTPUT: projects/circle-ds-pipelines/topics/mantle
  ROOT_ENTITY_TYPE: block
  ENTITY_TYPES: block,transaction,log,token_transfer
  GCS_PREFIX: gs://circle-blockchain-etl-streaming/mantle
  CHAIN: mantle
  CHAIN_TYPE: ethereum
  LAG_BLOCKS: 30
  BLOCK_BATCH_SIZE: 250

stream:
  resources:
    requests:
      memory: "1024Mi"
    limits:
      memory: "2048Mi"