config:
  PROVIDER_URI: https://mainnet.era.zksync.io
  STREAM_OUTPUT: projects/circle-ds-pipelines/topics/zksync
  ROOT_ENTITY_TYPE: block
  ENTITY_TYPES: block,transaction,log,token_transfer
  GCS_PREFIX: gs://circle-blockchain-etl-streaming/zksync
  CHAIN: zksync
  CHAIN_TYPE: ethereum
  LAG_BLOCKS: 30
  BLOCK_BATCH_SIZE: 250