config:
  PROVIDER_URI: https://dry-lingering-borough.zksync-mainnet.quiknode.pro/2166407ad6061ca905bd1dadfad62bffb8cf0a2f/
  STREAM_OUTPUT: projects/circle-ds-pipelines/topics/zksync
  ROOT_ENTITY_TYPE: block
  ENTITY_TYPES: block,transaction,log,token_transfer
  GCS_PREFIX: gs://circle-blockchain-etl-streaming/zksync
  CHAIN: zksync
  CHAIN_TYPE: ethereum
  LAG_BLOCKS: 30
  BLOCK_BATCH_SIZE: 50

stream:
  resources:
    requests:
      memory: "2048Mi"
      cpu: "300m"
    limits:
      memory: "4096Mi"
      cpu: "800m"